### PR TITLE
Fix "start on sunday"

### PR DESCRIPTION
**Pull request by aragaer**
Trying to fix the issue in #185

### CODE REVIEW

**Comment by cslux** [comment]
Thanks for your contribution. Do have an example journal file, and configuration to share which reproduce this issue?

**Comment by aragaer** [comment]
My configuration is
```emacs-lisp
  :custom
  (org-journal-file-type 'weekly)
  (org-journal-date-format "%A, %Y-%m-%d")
  (org-journal-start-on-weekday 7)
```
Today (2020-01-17, Sunday) I tried to create an entry for today, but I already had a TODO item in journal for tomorrow (2020-01-18, Monday). With the code above I've managed to do that.
```
#+startup: overview
#+startup: shrink
#+category: journal
* Monday, 2021-01-18
:PROPERTIES:
:CREATED:  20210118
:END:
** TODO Something
SCHEDULED: <2021-01-18 Mon>
```

**Comment by cslux** [comment]
I was able to reproduce it with a test, and indeed 0 is wrong and 7 is correct. When 0, the journal entry would be added to the journal file 20210110, instead of the correct one 20210117.

Can you remove the second commit (https://github.com/bastibe/org-journal/pull/322/commits/5ca5b2f24a4e51fcf53552987e53df95ea5ec2d1) from this PR please. I don't see why these changes are necessary. 

Also please move sunday to the end of the list (numerical sorted).

**Comment by aragaer** [comment]
Second commit is not directly related to this, it's about inserting the new entry into existing file at the correct position. Current implementation gathers the list of all already present entries in descending order (starting from future ones and moving to past ones) and tries to find a first entry that is "older" than new. If that succeeds, new entry is inserted after such entry. However if all entries are "younger" than the new inserted one, no such entry matches and new entry is inserted in the end. In example I provided, Sunday entry would be added at the end of file, after the Monday entry (it should be the other way). My second commit fixes exactly that issue.

I can submit a different PR for that if necessary.

**Comment by cslux** [comment]
It should indeed be added before Monday when start of weekday is set to
Sunday. Please create a new PR for that. I'll create a test case for it which
proofs the current implementation is wrong.

**Comment by cslux** [comment]
Appreciate your help! Merged.

**Pull request merged**
