### PR TITLE
Add highlight to org-journal-search-print-results

### PR DESCRIPTION
**Pull request by aJchemist**

### CODE REVIEW

**Comment by bastibe** [comment]
Thank you for this idea! This is pretty cool!

This requires highlight.el to be installed, right? I would prefer to not include this dependency. Do you know if there is a way to achieve this highlight without using highlight.el?

**Comment by aJchemist** [comment]
@bastibe Ooops! I knew highlight.el is built-in emacs library. For now I have commited a workaround.

**Comment by bastibe** [comment]
Very cool, this is a neat solution. Do you want to look for a way to do this without using highlight.el, or rather push this as a new version as soon as possible? 

It is probably relatively easy to implement this highlight using overlays, if you want to try your hand at that.

**Comment by aJchemist** [comment]
@bastibe ping

**Comment by vkazanov** [comment]
@aJchemist 

Just  my two cents. 

1. Great idea! I should have done this from start (I implemented the search).

2. It is generally better to use text properties for highlighting anything as overlays become slow really, REALLY easy. 

There some single linked lists behind the overlay mechanism, which are always linear.  I even discussed the problem on emacs-devel mailing list and will probably switch to a tree some day sunny day, but for now it's only useful for 5-10 overlays/buffer.

**Comment by aJchemist** [comment]
@vkazanov Nice point :+1: thx for telling your clean solution.

**Comment by bastibe** [comment]
Sorry, I was on vacation and did not check my emails. I like this a lot, though!

**Comment by bastibe** [comment]
I am so sorry for not uploading this to melpa/marmalade earlier! I completely forgot about this.

I am uploading a new version right now.

**Comment by aJchemist** [comment]
@bastibe nvm, luckily I'm not a user of emacs package system; melpa/marmalade or others.

Anyway. cool!

**Pull request merged**
