### PR TITLE
Add Spacemacs layer guide to README

### PR DESCRIPTION
**Pull request by borgnix**
Hi. I really enjoy the journaling experience with `org-journal`, so I made a Spacemacs layer to provide Spacemacs-style key binding wrapping. I would like to add a spacemacs layer guide to README in case that there are other Spacemacs users who need it.
Again, thanks for your work on `org-journal`.

### CODE REVIEW

**Comment by bastibe** [comment]
Very nice! Could this spacemacs layer be included directly in org-journal without breaking non-spacemacsen's configs?

**Comment by borgnix** [comment]
This layer is specifically for Spacemacs users. It functions well with spacemacs layer mechanism, provides out of box `org-journal` experience for spacemacs users, but would be useless without spacemacs. It will not affect non-spacemacs' configs.

**Comment by bastibe** [comment]
Could we include this layer into org-journal itself, or do you want to keep it in your own repository?

**Comment by borgnix** [comment]
Tthe layer is a wrapper for org-journal. It's not an enhance to `org-journal` itself. It could be integrated into org-journal repo, but it would be totally useless for non-spacemacs users, and not very convenient for spacemacs users to install it(by cloning the whole repo into `.emacs.d/private` and let melpa manage `org-journal` package). so I think it would be better to keep it separate.

**Comment by bastibe** [comment]
OK, thank you for the clarification.

**Comment by borgnix** [comment]
Sorry, I'm not very good at writing README. Would it be okay if i change it to:

To use org-journal on spacemacs, you could :

1. `git clone https://github.com/borgnix/spacemacs-journal.git ~/.emacs.d/private/journal`
2. add it to your ~/.spacemacs. You will need to add `journal` to the existing dotspacemacs-configuration-layers list in this file.

Manuel of `journal` layer could be found at https://github.com/borgnix/spacemacs-journal

**Comment by bastibe** [comment]
Of course, that would be very good. 

- Please set all variable names and paths as code
- Please change the last sentence to "The manual of the `journal` layer can be found at ..."

**Comment by borgnix** [comment]
Okay, thanks for the review.

**Comment by bastibe** [comment]
Thank you very much!

**Comment by vkazanov** [comment]
@bastibe , how about moving Spacemacs-related comment into FAQ? Or to the bottom of the README? It feels a bit out of place near Synopsys. :-)

**Comment by bastibe** [comment]
Good thinking. Will do.

**Comment by bastibe** [comment]
done.

**Comment by vkazanov** [comment]
Cool! :-) FAQ doesn't sound so negative now :-)

**Pull request merged**
