### PR TITLE
Add org-journal-open-current-journal-file interactive function

### PR DESCRIPTION
**Pull request by psibi**
This allows me to open current journal file easily.

### CODE REVIEW

**Comment by psibi** [comment]
@bastibe When I have multiple buffers open, I use this function frequently to go the current journal file. Is there any existing function which can be used to do that (I actually went briefly through the existing functions, before just writing this out) ?

**Comment by bastibe** [comment]
I usually use `org-journal-new-entry` with a prefix in this situation, i.e. `C-u C-c C-j`.

**Comment by psibi** [comment]
@bastibe Using that function will interfere with the variable `org-journal-skip-carryover-drawers` and will deletes the drawers if it is set (which in my case is set) and hence cannot be used in my current workflow.

**Comment by cslux** [comment]
> @bastibe Using that function will interfere with the variable `org-journal-skip-carryover-drawers` and will deletes the drawers if it is set (which in my case is set) and hence cannot be used in my current workflow.

That sounds like a bug!

@bastibe I think @psibi wants to just open the current journal file without creating a new heading/entry. org-journal-new-entry called with a prefix argument doesn't insert an entry, but does insert a heading though. 

We could also supercharge org-journal-new-entry with two prefix arguments. If two prefix args are given just open the current journal file, and if it doesn't exists, create it. What do you think @psibi @bastibe?

**Comment by psibi** [comment]
> @bastibe I think @psibi wants to just open the current journal file without creating a new heading/entry. org

Yeah, that's right.

> We could also supercharge org-journal-new-entry with two prefix arguments. If two prefix args are given just open the current journal file, and if it doesn't exists, create it. What do you think @psibi @bastibe?

Sounds good to me.

**Comment by bastibe** [comment]
> We could also supercharge org-journal-new-entry with two prefix arguments. If two prefix args are given just open the current journal file, and if it doesn't exists, create it. What do you think @psibi @bastibe?

Honestly, most of the time I actually just want to open the most recent journal entry without adding anything new just yet. For this application, sticking with @psibi's PR is actually more convenient than adding yet another modifier to `org-journal-new-entry`. (Although we might want to expand the PR to open the *most recent* entry instead of *today's*).

**Comment by cslux** [comment]
> Honestly, most of the time I actually just want to open the most recent journal entry without adding anything new just yet. For this application, sticking with @psibi's PR is actually more convenient than adding yet another modifier to `org-journal-new-entry`. (Although we might want to expand the PR to open the _most recent_ entry instead of _today's_).

Sounds good to me.

**Comment by cslux** [comment]
Do we want to bind it to a key, or should we left it to the user?

**Comment by bastibe** [comment]
Looks good to me!

**Pull request merged**
