### PR TITLE
Add a encryption feature

### PR DESCRIPTION
**Pull request by bigeye**
When a user save journal file which has 'org-crypt-tag-matcher',
org-crypt will encrypt this entry. With this tag, Try to
encrypt/decrypt their journal whenever a user saves/opens their
journals.

### CODE REVIEW

**Comment by k0377** [comment]
Any updates on this? I would really like to see an encryption feature in my personal diary!

**Comment by bastibe** [comment]
I'm afraid I currently don't have time to look into this. If anyone else would want to do this, I'd be grateful for it, though.

**Comment by punchagan** [comment]
I [rebased](https://github.com/punchagan/org-journal/tree/org-crypt) this to work with the latest master.

**Comment by punchagan** [comment]
I have added a customizable variable to determine when to do the encryption. Encryption is not setup automatically, now and needs to be done manually.

**Comment by punchagan** [comment]
I've pushed a commit to make this happen automatically in `org-journal`. All one would need to do is to enable encryption by setting `org-journal-enable-encryption`.

**Comment by bastibe** [comment]
Thank you for your work on this!

I don't quite like how this asks for the passphrase on every encrypt, but I guess this is in org-crypt's hand now. Anyway, I also undid the changes you did to the way files are opened/viewed--they looked good at first glance, but actually didn't work reliably. For more detail, see 1dd27c7005f8372f92c9571726a2793ba3c407f7.

**Comment by punchagan** [comment]
I haven't yet tried this, but it looks like it should be possible to setup `gpg-agent` to cache pass-phrases.

**Pull request closed without merging**
